- id: yapf
  name: YAPF formatter
  entry: hooks/run_yapf.sh
  language: script
  files: \.py$

- id: docformatter
  name: Docformatter cleanup
  entry: hooks/run_docformatter.sh
  language: script
  files: \.py$

- id: fix_docs
  name: Capitalize docstring param descriptions, newline between last :param and :return, no newlines after :return
  entry: hooks/fix_docs
  language: python
  files: \.py$
  pass_filenames: true